<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P3ALAP-G01FTQF" ignored="0" name="Test2" tests="4" failures="2" timestamp="05 Nov 2019 05:42:17 GMT" time="0.057" errors="0">
  <testcase name="test1" time="0.012" classname="testngFeature.DemoAssertEquals">
    <failure type="java.lang.AssertionError" message="expected [Hello] but found [Hello1]">
      <![CDATA[java.lang.AssertionError: expected [Hello] but found [Hello1]
at testngFeature.DemoAssertEquals.test1(DemoAssertEquals.java:11)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.003" classname="testngFeature.DemoAssertEquals"/>
  <testcase name="test3" time="0.002" classname="testngFeature.DemoAssertEquals"/>
  <testcase name="test4" time="0.003" classname="testngFeature.DemoAssertEquals">
    <failure type="java.lang.AssertionError" message="Failing the test">
      <![CDATA[java.lang.AssertionError: Failing the test
at testngFeature.DemoAssertEquals.test4(DemoAssertEquals.java:40)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
</testsuite> <!-- Test2 -->
